server:
  port: 10001

spring:
  application:
    name: @artifactId@

eureka:
  client:
    # 是否注册自己到 Eureka
    register-with-eureka: false
    # 指示该客户端是否应从eureka服务器获取eureka注册表信息。
    fetch-registry: false

    serviceUrl:
      defaultZone: http://127.0.0.1:10001/eureka/
  server:
    # 清理无效节点时间间隔（单位毫秒，默认是60*1000
    eviction-interval-timer-in-ms: 3000
    responseCacheAutoExpirationInSeconds: 180
    response-cache-update-interval-ms: 3000

