server:
  port: 10001

spring:
  application:
    name: @artifactId@

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 3000
    responseCacheAutoExpirationInSeconds: 180
    response-cache-update-interval-ms: 3000

